<?php

/**
 * @file
 * Contains the geofield_map.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function geofield_map_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.geofield_map':
      $output .= '<h3>' . t('Geofield Map About') . '</h3>';
      $output .= '<p>' . t('(Google and Leaflet) Map widget and formatter for Geofield.') . '</p>';
      $output .= '<p>' . t('Allow to use a google map v3 map to input a location.') . '</p>';
      $output .= '<p>' . t('A quick text input + geocode allow you to specify an address.') . '</p>';
      $output .= '<p>' . t('You can drag and drop the marker to narrow the position.') . '</p>';
      $output .= '<p>' . t('For more info: @readme', [
        '@readme' => Link::fromTextAndUrl(t('Readme.md'), Url::fromUri('base:/' . drupal_get_path('module', 'geofield_map') . '/README.md', ['attributes' => ['target' => '_blank']]))->toString(),
      ]) . '</p>';

  }
  return $output;
}

/**
 * Implements hook_theme().
 */
function geofield_map_theme($existing, $type, $theme, $path) {
  return array(
    'geofield_google_map' => array(
      'variables' => array(
        'mapid' => NULL,
        'height' => '400px',
        'width' => '100%',
      ),
    ),
  );
}

/**
 * Load all Geofield Google Map client files and return markup for a map.
 *
 * @param array $js_settings
 *   The map rendering data.
 *
 * @return array
 *   The returned render array.
 */
function geofield_map_googlemap_render($js_settings) {

  $render_array = [
    '#theme' => 'geofield_google_map',
    '#mapid' => $js_settings['mapid'],
    '#height' => $js_settings['map_settings']['map_dimensions']['height'],
    '#width' => $js_settings['map_settings']['map_dimensions']['width'],
    '#attached' => [
      'library' => [
        'geofield_map/geojson',
        'geofield_map/geofield_gmap',
      ],
      'drupalSettings' => [
        'geofield_google_map' => [$js_settings['mapid'] => $js_settings],
      ],
    ],
    '#cache' => [
      'contexts' => ['url.path', 'url.query_args'],
    ],
  ];

  if ($js_settings['map_settings']['map_markercluster']['markercluster_control']) {
    $render_array['#attached']['library'][] = 'geofield_map/marker_cluster';
  }

  return $render_array;
}
